name: General run

on:
  workflow_dispatch:
    inputs:
      MY_PRODUCT:
        description: 'Your product'
        required: true
        default: 'technology' # You can change the default value
      MY_TARGET_AUDIENCE:
        description: 'Your target audience'
        required: true
        default: '50+ emploees companies' # You can change the default value
      TG_CHAT_ID:
        description: 'tg chat_id ex: 123456789'
        required: true
        default: 'prices' # You can change the default value        
      TG_BOT_TOKEN:
        description: 'ex: '
        required: true
        default: '' # You can change the default value  
      MY_OPENAI_KEY:
        description: 'MY_OPENAI_KEY sk-... '
        required: false
        default: '' # You can change the default value        

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'

    - name: Check if secrets OPENAI_API_KEY_DEFAULT is set
      run: |
        if [ -z "${{ secrets.OPENAI_API_KEY_DEFAULT }}" ]; then
          echo "OPENAI_API_KEY_DEFAULT is not set!"
          exit 1
        else
          echo "OPENAI_API_KEY_DEFAULT is set!"
        fi  # Add this 'fi' to close the if statement

    - name: Install XVFB and other libs
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb unrar p7zip-full

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: playwright install chromium
    - name: Prepare git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git config pull.rebase false
    - name: Run python scripts
      env:
        OPENAI_API_KEY_DEFAULT: ${{ secrets.OPENAI_API_KEY_DEFAULT }}
        MY_PRODUCT: ${{ github.event.inputs.MY_PRODUCT }}
        MY_TARGET_AUDIENCE: ${{ github.event.inputs.MY_TARGET_AUDIENCE }}
        TG_CHAT_ID: ${{ github.event.inputs.TG_CHAT_ID }}
        TG_BOT_TOKEN: ${{ github.event.inputs.TG_BOT_TOKEN }}
        BASE_GPTV: "gpt-3.5-turbo-0125"
        SMART_GPTV: "gpt-3.5-turbo-0125"
        MY_OPENAI_KEY: ${{ github.event.inputs.MY_OPENAI_KEY }}
      run: |
        python 1loadSerp.py
        git add -A
        git diff --cached --exit-code || git commit -m "($GITHUB_WORKFLOW) - 1loadSerp.py"
        git pull
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || true
